allowBuilds:
  '@parcel/watcher': true
  core-js: false
  esbuild: true
  protobufjs: false
  unrs-resolver: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - protobufjs
  - unrs-resolver
